# Generated by Django 3.0.7 on 2020-06-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_manager_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='country',
            field=models.TextField(default=''),
        ),
    ]
